# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestion_personnel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import qdarkstyle

class Ui_Gestion_Personnel(object):
    def setupUi(self, Gestion_Personnel):
        Gestion_Personnel.setObjectName("Gestion_Personnel")
        Gestion_Personnel.resize(1928, 1075)
        self.downloadPDF = QtWidgets.QPushButton(Gestion_Personnel)
        self.downloadPDF.setGeometry(QtCore.QRect(480, 677, 131, 41))
        self.downloadPDF.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border: 2px solid #792382;\n"
"    color: #792382;\n"
"    border-radius: 5px;\n"
"    background-image: url(\"D:/ESPRIT/c++/Projet/ProjetC++/images/download.svg\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    padding-left: 30px; /* Ajustez ceci selon la taille de votre image */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43aff7;\n"
"}\n"
"\n"
"\n"
"")
        self.downloadPDF.setObjectName("downloadPDF")
        self.stat = QtWidgets.QPushButton(Gestion_Personnel)
        self.stat.setGeometry(QtCore.QRect(460, 107, 111, 41))
        self.stat.setStyleSheet("QPushButton {\n"
"    /*padding: 10px 20px;*/\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border: 2px solid #792382;\n"
"    color: #792382;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43aff7;\n"
"}\n"
"")
        self.stat.setObjectName("stat")
        self.logo = QtWidgets.QLabel(Gestion_Personnel)
        self.logo.setGeometry(QtCore.QRect(60, 37, 121, 91))
        self.logo.setStyleSheet("\n"
"    background-image: url(\"D:/ESPRIT/c++/Projet/ProjetC++/images/logo.png\");")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../../../Documents/interface à bechir/interface ├á bechir/images/logo.png"))
        self.logo.setObjectName("logo")
        self.chat = QtWidgets.QPushButton(Gestion_Personnel)
        self.chat.setGeometry(QtCore.QRect(20, 887, 161, 41))
        self.chat.setStyleSheet("QPushButton {\n"
"    /*padding: 10px 20px;*/\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border: 2px solid #792382;\n"
"    color: #792382;\n"
"    border-radius: 5px;\n"
"background-color:white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43aff7;\n"
"}\n"
"\n"
"\n"
"")
        self.chat.setObjectName("chat")
        self.triS = QtWidgets.QPushButton(Gestion_Personnel)
        self.triS.setGeometry(QtCore.QRect(1710, 117, 111, 41))
        self.triS.setStyleSheet("QPushButton {\n"
"    /*padding: 10px 20px;*/\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border: 2px solid #792382;\n"
"    color: #792382;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43aff7;\n"
"}\n"
"")
        self.triS.setObjectName("triS")
        self.formLayoutWidget_2 = QtWidgets.QWidget(Gestion_Personnel)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 147, 400, 655))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_41 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_41.setStyleSheet("QLabel {\n"
"    font-size: 22px;\n"
"    color: white; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"}\n"
"")
        self.label_41.setObjectName("label_41")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.scan_CIN = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.scan_CIN.setObjectName("scan_CIN")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.scan_CIN)
        self.label_40 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_40.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: white; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"}\n"
"")
        self.label_40.setObjectName("label_40")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.CIN = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.CIN.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 2px solid #43aff7;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #2ecc71; /* Couleur de la bordure lorsqu\'il est activé */\n"
"}\n"
"")
        self.CIN.setObjectName("CIN")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.CIN)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_30.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: white; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"}\n"
"")
        self.label_30.setObjectName("label_30")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.nom = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.nom.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 2px solid #43aff7;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #2ecc71; /* Couleur de la bordure lorsqu\'il est activé */\n"
"}\n"
"")
        self.nom.setObjectName("nom")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.nom)
        self.label_31 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_31.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: white; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"}\n"
"")
        self.label_31.setObjectName("label_31")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.prenom = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.prenom.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 2px solid #43aff7;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #2ecc71; /* Couleur de la bordure lorsqu\'il est activé */\n"
"}\n"
"")
        self.prenom.setObjectName("prenom")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.prenom)
        self.label_32 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_32.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: white; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"}\n"
"")
        self.label_32.setObjectName("label_32")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.age = QtWidgets.QDateEdit(self.formLayoutWidget_2)
        self.age.setStyleSheet("QDateEdit {\n"
"    \n"
"    padding: 5px;\n"
"    border: 2px solid #43aff7;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left: 2px solid #3498db;\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    border-color: #2ecc71; /* Couleur de la bordure lorsqu\'il est activé */\n"
"}\n"
"")
        self.age.setObjectName("age")
        self.formLayout_4.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.age)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_33.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: white; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"}\n"
"")
        self.label_33.setObjectName("label_33")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.email = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.email.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 2px solid #43aff7;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #2ecc71; /* Couleur de la bordure lorsqu\'il est activé */\n"
"}\n"
"")
        self.email.setObjectName("email")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.email)
        self.label_34 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_34.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: white; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"}\n"
"")
        self.label_34.setObjectName("label_34")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.numtel = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.numtel.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 2px solid #43aff7;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #2ecc71; /* Couleur de la bordure lorsqu\'il est activé */\n"
"}\n"
"")
        self.numtel.setObjectName("numtel")
        self.formLayout_4.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.numtel)
        self.label_35 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_35.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: white; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"}\n"
"")
        self.label_35.setObjectName("label_35")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.H = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.H.setStyleSheet("QRadioButton {\n"
"    padding: 5px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 2px solid #43aff7;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #2ecc71; /* Couleur de fond lorsque sélectionné */\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"    border-color: #3498db; /* Couleur de la bordure au survol */\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover {\n"
"    background-color: #2ecc71; /* Couleur de fond lorsque sélectionné et au survol */\n"
"}\n"
"\n"
"QRadioButton::indicator::unchecked {\n"
"    color: #333; /* Text color for unchecked state */\n"
"}\n"
"\n"
"QRadioButton::indicator::checked {\n"
"    color: #2ecc71; /* Text color when checked */\n"
"}")
        self.H.setChecked(True)
        self.H.setObjectName("H")
        self.formLayout_4.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.H)
        self.F = QtWidgets.QRadioButton(self.formLayoutWidget_2)
        self.F.setStyleSheet("QRadioButton {\n"
"    padding: 5px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 2px solid #43aff7;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #2ecc71; /* Couleur de fond lorsque sélectionné */\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.F.setObjectName("F")
        self.formLayout_4.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.F)
        self.label_36 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_36.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: white; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"}\n"
"")
        self.label_36.setObjectName("label_36")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.adresse = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.adresse.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 2px solid #43aff7;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #2ecc71; /* Couleur de la bordure lorsqu\'il est activé */\n"
"}\n"
"")
        self.adresse.setObjectName("adresse")
        self.formLayout_4.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.adresse)
        self.label_37 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_37.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: white; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"}\n"
"")
        self.label_37.setObjectName("label_37")
        self.formLayout_4.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.salaire = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.salaire.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 2px solid #43aff7;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #2ecc71; /* Couleur de la bordure lorsqu\'il est activé */\n"
"}\n"
"")
        self.salaire.setObjectName("salaire")
        self.formLayout_4.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.salaire)
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_38.setStyleSheet("QLabel {\n"
"    font-size: 18px;\n"
"    color: white; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"}\n"
"")
        self.label_38.setObjectName("label_38")
        self.formLayout_4.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.Role = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.Role.setStyleSheet("padding: 5px;\n"
"    border: 2px solid #43aff7;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    color: #333")
        self.Role.setObjectName("Role")
        self.Role.addItem("")
        self.Role.setItemText(0, "")
        self.Role.addItem("")
        self.Role.addItem("")
        self.Role.addItem("")
        self.Role.addItem("")
        self.Role.addItem("")
        self.Role.addItem("")
        self.formLayout_4.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.Role)
        self.label_39 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_39.setText("")
        self.label_39.setPixmap(QtGui.QPixmap("../../../AppData/Local/Temp/b6651d8d-1e9f-45ec-8183-973f3ea7bf13_interface à bechir.zip.f13/PROJET C++/back.jpg"))
        self.label_39.setObjectName("label_39")
        self.formLayout_4.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.label_39)
        self.ajouter = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.ajouter.setStyleSheet("QPushButton {\n"
"    /*padding: 10px 20px;*/\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border: 2px solid #792382;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43aff7;\n"
"}\n"
"\n"
"")
        self.ajouter.setObjectName("ajouter")
        self.formLayout_4.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.ajouter)
        self.Annuler = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.Annuler.setStyleSheet("QPushButton {\n"
"    /*padding: 10px 20px;*/\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border: 2px solid #792382;\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43aff7;\n"
"}\n"
"\n"
"\n"
"")
        self.Annuler.setObjectName("Annuler")
        self.formLayout_4.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.Annuler)
        self.frame = QtWidgets.QFrame(Gestion_Personnel)
        self.frame.setGeometry(QtCore.QRect(1650, 117, 51, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.asc = QtWidgets.QRadioButton(self.frame)
        self.asc.setGeometry(QtCore.QRect(0, 0, 97, 20))
        self.asc.setStyleSheet("color:white")
        self.asc.setObjectName("asc")
        self.desc = QtWidgets.QRadioButton(self.frame)
        self.desc.setGeometry(QtCore.QRect(0, 20, 97, 20))
        self.desc.setStyleSheet("color:white")
        self.desc.setObjectName("desc")
        self.label_3 = QtWidgets.QLabel(Gestion_Personnel)
        self.label_3.setGeometry(QtCore.QRect(860, 37, 271, 41))
        self.label_3.setStyleSheet("QLabel {\n"
"    font-size: 22px;\n"
"    color: #792382; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(Gestion_Personnel)
        self.frame_2.setGeometry(QtCore.QRect(1260, 97, 181, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.ascN = QtWidgets.QPushButton(self.frame_2)
        self.ascN.setGeometry(QtCore.QRect(70, 20, 41, 41))
        self.ascN.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../untitled/images/ascA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ascN.setIcon(icon)
        self.ascN.setObjectName("ascN")
        self.descN = QtWidgets.QPushButton(self.frame_2)
        self.descN.setGeometry(QtCore.QRect(120, 20, 41, 41))
        self.descN.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../untitled/images/descA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.descN.setIcon(icon1)
        self.descN.setObjectName("descN")
        self.label_42 = QtWidgets.QLabel(self.frame_2)
        self.label_42.setGeometry(QtCore.QRect(10, 20, 51, 41))
        self.label_42.setStyleSheet("QLabel {\n"
"    font-size: 22px;\n"
"    color: #792382; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"}\n"
"")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(Gestion_Personnel)
        self.label_43.setGeometry(QtCore.QRect(720, 337, 61, 41))
        self.label_43.setText("")
        self.label_43.setPixmap(QtGui.QPixmap("../../../AppData/Local/Temp/Downloads/search (1).svg"))
        self.label_43.setObjectName("label_43")
        self.tableW = QtWidgets.QTableWidget(Gestion_Personnel)
        self.tableW.setGeometry(QtCore.QRect(420, 180, 1501, 481))
        self.tableW.setObjectName("tableW")
        self.tableW.setColumnCount(0)
        self.tableW.setRowCount(0)
        self.label_44 = QtWidgets.QLabel(Gestion_Personnel)
        self.label_44.setGeometry(QtCore.QRect(1130, 467, 61, 31))
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap("../../../AppData/Local/Temp/Downloads/edit.svg"))
        self.label_44.setObjectName("label_44")
        self.search = QtWidgets.QLineEdit(Gestion_Personnel)
        self.search.setGeometry(QtCore.QRect(590, 107, 331, 41))
        self.search.setStyleSheet("QLineEdit {\n"
"    padding: 5px;\n"
"    border: 2px solid #43aff7;\n"
"    border-radius: 5px;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"    padding-left: 30px; /* Ajustez ceci selon la taille de votre image */\n"
"    background-image: url(\"D:/ESPRIT/c++/Projet/ProjetC++/images/search.svg\");\n"
"    background-repeat: no-repeat;\n"
"\n"
"    background-position: left center;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #666; /* Couleur du texte de repère */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #2ecc71; /* Couleur de la bordure lorsqu\'il est activé */\n"
"}\n"
"")
        self.search.setObjectName("search")
        self.label = QtWidgets.QLabel(Gestion_Personnel)
        self.label.setGeometry(QtCore.QRect(-20, 0, 2081, 1081))
        self.label.setStyleSheet("background-image: url(\"D:/ESPRIT/c++/Projet/ProjetC++/images/back.jpg\");")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_45 = QtWidgets.QLabel(Gestion_Personnel)
        self.label_45.setGeometry(QtCore.QRect(720, 337, 61, 41))
        self.label_45.setText("")
        self.label_45.setPixmap(QtGui.QPixmap("../../../AppData/Local/Temp/Downloads/search (1).svg"))
        self.label_45.setObjectName("label_45")
        self.triD = QtWidgets.QPushButton(Gestion_Personnel)
        self.triD.setGeometry(QtCore.QRect(1490, 117, 141, 41))
        self.triD.setStyleSheet("QPushButton {\n"
"    /*padding: 10px 20px;*/\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border: 2px solid #792382;\n"
"    color: #792382;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43aff7;\n"
"}\n"
"")
        self.triD.setObjectName("triD")
        self.menu = QtWidgets.QPushButton(Gestion_Personnel)
        self.menu.setGeometry(QtCore.QRect(20, 827, 161, 41))
        self.menu.setStyleSheet("QPushButton {\n"
"    /*padding: 10px 20px;*/\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border: 2px solid #792382;\n"
"    color: #792382;\n"
"    border-radius: 5px;\n"
"background-color:white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43aff7;\n"
"}\n"
"\n"
"\n"
"")
        self.menu.setObjectName("menu")
        self.label_46 = QtWidgets.QLabel(Gestion_Personnel)
        self.label_46.setGeometry(QtCore.QRect(1130, 507, 61, 31))
        self.label_46.setText("")
        self.label_46.setPixmap(QtGui.QPixmap("../../../AppData/Local/Temp/Downloads/edit.svg"))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(Gestion_Personnel)
        self.label_47.setGeometry(QtCore.QRect(1130, 507, 61, 31))
        self.label_47.setText("")
        self.label_47.setPixmap(QtGui.QPixmap("../../../AppData/Local/Temp/Downloads/edit.svg"))
        self.label_47.setObjectName("label_47")
        self.logout = QtWidgets.QPushButton(Gestion_Personnel)
        self.logout.setGeometry(QtCore.QRect(20, 940, 161, 41))
        self.logout.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border: 2px solid #792382;\n"
"    color: #792382;\n"
"    border-radius: 5px;\n"
"    background-image: url(\"D:/ESPRIT/c++/Projet/ProjetC++/images/download.svg\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: left center;\n"
"    padding-left: 30px; /* Ajustez ceci selon la taille de votre image */\n"
"background-color:white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43aff7;\n"
"}\n"
"\n"
"\n"
"")
        self.logout.setObjectName("logout")
        self.OnOffModification = QtWidgets.QCheckBox(Gestion_Personnel)
        self.OnOffModification.setGeometry(QtCore.QRect(840, 660, 421, 31))
        self.OnOffModification.setStyleSheet("\n"
"    font-size: 22px;\n"
"    color: #792382; /* Couleur du texte */\n"
"    font-weight: bold; /* Gras */\n"
"    /* Ajoutez d\'autres styles selon vos besoins */\n"
"\n"
"")
        self.OnOffModification.setObjectName("OnOffModification")
        self.widget = QtWidgets.QWidget(Gestion_Personnel)
        self.widget.setGeometry(QtCore.QRect(410, 150, 1541, 641))
        self.widget.setObjectName("widget")
        self.statOFF = QtWidgets.QPushButton(Gestion_Personnel)
        self.statOFF.setGeometry(QtCore.QRect(1760, 860, 93, 28))
        self.statOFF.setStyleSheet("QPushButton {\n"
"    /*padding: 10px 20px;*/\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border: 2px solid #792382;\n"
"    color: #792382;\n"
"    border-radius: 5px;\n"
"background-color:white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43aff7;\n"
"}\n"
"\n"
"\n"
"")
        self.statOFF.setObjectName("statOFF")
        self.commands = QtWidgets.QTextEdit(Gestion_Personnel)
        self.commands.setGeometry(QtCore.QRect(1330, 670, 591, 231))
        self.commands.setObjectName("commands")
        self.confirm = QtWidgets.QPushButton(Gestion_Personnel)
        self.confirm.setGeometry(QtCore.QRect(1790, 910, 131, 41))
        self.confirm.setObjectName("confirm")
        self.darkMode = QtWidgets.QPushButton(Gestion_Personnel)
        self.darkMode.setGeometry(QtCore.QRect(1760, 30, 111, 41))
        self.darkMode.setStyleSheet("QPushButton {\n"
"    /*padding: 10px 20px;*/\n"
"    padding: 5px;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border: 2px solid #792382;\n"
"    color: #792382;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #43aff7;\n"
"}\n"
"")
        self.darkMode.setObjectName("darkMode")
        self.darkMode.clicked.connect(self.toggle_dark_mode)
        # Initial light mode stylesheet
        self.light_mode_stylesheet = self.darkMode.styleSheet()

        self.confirm.raise_()
        self.commands.raise_()
        self.widget.raise_()
        self.statOFF.raise_()
        self.label.raise_()
        self.downloadPDF.raise_()
        self.stat.raise_()
        self.logo.raise_()
        self.chat.raise_()
        self.triS.raise_()
        self.formLayoutWidget_2.raise_()
        self.frame.raise_()
        self.label_3.raise_()
        self.frame_2.raise_()
        self.label_43.raise_()
        self.tableW.raise_()
        self.label_44.raise_()
        self.search.raise_()
        self.label_45.raise_()
        self.triD.raise_()
        self.menu.raise_()
        self.label_46.raise_()
        self.label_47.raise_()
        self.logout.raise_()
        self.OnOffModification.raise_()
        self.darkMode.raise_()

        self.retranslateUi(Gestion_Personnel)
        QtCore.QMetaObject.connectSlotsByName(Gestion_Personnel)

    def retranslateUi(self, Gestion_Personnel):
        _translate = QtCore.QCoreApplication.translate
        Gestion_Personnel.setWindowTitle(_translate("Gestion_Personnel", "Dialog"))
        self.downloadPDF.setText(_translate("Gestion_Personnel", "Télécharger"))
        self.stat.setText(_translate("Gestion_Personnel", "Statistique"))
        self.chat.setText(_translate("Gestion_Personnel", "CHAT"))
        self.triS.setText(_translate("Gestion_Personnel", "Trier(Salaire)"))
        self.label_41.setText(_translate("Gestion_Personnel", "Ajouter un employee"))
        self.scan_CIN.setText(_translate("Gestion_Personnel", "Scanner votre cin"))
        self.label_40.setText(_translate("Gestion_Personnel", "CIN"))
        self.CIN.setPlaceholderText(_translate("Gestion_Personnel", "CIN"))
        self.label_30.setText(_translate("Gestion_Personnel", "Nom"))
        self.nom.setPlaceholderText(_translate("Gestion_Personnel", "Nom"))
        self.label_31.setText(_translate("Gestion_Personnel", "Prénom"))
        self.prenom.setPlaceholderText(_translate("Gestion_Personnel", "Prenom"))
        self.label_32.setText(_translate("Gestion_Personnel", "Date de naissance"))
        self.label_33.setText(_translate("Gestion_Personnel", "E-mail"))
        self.email.setPlaceholderText(_translate("Gestion_Personnel", "email"))
        self.label_34.setText(_translate("Gestion_Personnel", "Numero telephone"))
        self.numtel.setPlaceholderText(_translate("Gestion_Personnel", "Numero de telephone"))
        self.label_35.setText(_translate("Gestion_Personnel", "Sexe"))
        self.H.setText(_translate("Gestion_Personnel", "Homme"))
        self.F.setText(_translate("Gestion_Personnel", "Femme"))
        self.label_36.setText(_translate("Gestion_Personnel", "Adresse"))
        self.adresse.setPlaceholderText(_translate("Gestion_Personnel", "Adresse"))
        self.label_37.setText(_translate("Gestion_Personnel", "Salaire"))
        self.salaire.setPlaceholderText(_translate("Gestion_Personnel", "Salaire"))
        self.label_38.setText(_translate("Gestion_Personnel", "Role"))
        self.Role.setItemText(1, _translate("Gestion_Personnel", "Employee"))
        self.Role.setItemText(2, _translate("Gestion_Personnel", "Gestion_Personnels"))
        self.Role.setItemText(3, _translate("Gestion_Personnel", "Gestion_Oeuvres"))
        self.Role.setItemText(4, _translate("Gestion_Personnel", "Gestion_Participants"))
        self.Role.setItemText(5, _translate("Gestion_Personnel", "Gestion_Charites"))
        self.Role.setItemText(6, _translate("Gestion_Personnel", "Gestion_Evenements"))
        self.ajouter.setText(_translate("Gestion_Personnel", "Ajouter"))
        self.Annuler.setText(_translate("Gestion_Personnel", "Annuler"))
        self.asc.setText(_translate("Gestion_Personnel", "asc"))
        self.desc.setText(_translate("Gestion_Personnel", "desc"))
        self.label_3.setText(_translate("Gestion_Personnel", "Gestion des personnels"))
        self.label_42.setText(_translate("Gestion_Personnel", "Nom"))
        self.search.setPlaceholderText(_translate("Gestion_Personnel", "Rechercher.."))
        self.triD.setText(_translate("Gestion_Personnel", "Trier(dateNaiss)"))
        self.menu.setText(_translate("Gestion_Personnel", "MENU"))
        self.logout.setText(_translate("Gestion_Personnel", "Se deconnecter"))
        self.OnOffModification.setText(_translate("Gestion_Personnel", "Cocher pour Activer la Modification"))
        self.statOFF.setText(_translate("Gestion_Personnel", "CLOSE"))
        self.confirm.setText(_translate("Gestion_Personnel", "confirm"))
        self.darkMode.setText(_translate("Gestion_Personnel", "ModeSombre"))

def toggle_dark_mode(self):
        if self.is_dark_mode_enabled:
            # Apply light mode stylesheet
            self.darkMode.setStyleSheet(self.light_mode_stylesheet)
        else:
            # Apply dark mode stylesheet
            self.darkMode.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())

        # Toggle dark mode flag
        self.is_dark_mode_enabled = not self.is_dark_mode_enabled